"""Scenario runner for the ZhixingGraph economic simulation (whitepaper B.3.5).

Runs the scenario matrix and prints a Markdown results table. No dependencies.

    python3 sim/run.py            # run all scenarios, print table
    python3 sim/run.py --md       # same, plus write sim/RESULTS.md
"""

from __future__ import annotations

import sys

from model import SimConfig, Simulation

# --- Scenario matrix (B.3.5) --------------------------------------------------
SCENARIOS: dict[str, SimConfig] = {
    "baseline": SimConfig(),
    "inflation_stress": SimConfig(base_emission=32.0, demand_rate=0.5),
    "sybil_collusion": SimConfig(n_honest=30, n_spammers=15, n_colluders=10),
    "cold_start": SimConfig(n_honest=8, demand_base=0.1),
    "demand_shock": SimConfig(demand_rate=0.2, demand_base=0.1),
}

# What each scenario is expected to show (from the whitepaper).
EXPECT = {
    "baseline": "supply stable, low Gini, no attackers, honest ROI > 0",
    "inflation_stress": "high emission -> supply inflates (ceiling needed)",
    "sybil_collusion": "attacker ROI < 0 (loss) << honest ROI; fake pass -> 0",
    "cold_start": "sparse start still bootstraps the graph",
    "demand_shock": "demand collapse inflates but does not deadlock",
}


def run_all() -> dict[str, dict]:
    results = {}
    for name, cfg in SCENARIOS.items():
        results[name] = Simulation(cfg).run()
    return results


def to_markdown(results: dict[str, dict]) -> str:
    cols = [
        ("supply_delta", "Supply(gen→fin)"),
        ("avg_net_emission", "NetEmit/ep"),
        ("final_gini", "Gini"),
        ("final_valley_balance", "ValleyBal"),
        ("avg_fake_pass_rate", "FakePass"),
        ("avg_attacker_roi", "AtkROI"),
        ("final_honest_roi", "HonROI"),
    ]
    lines = []
    lines.append("| Scenario | " + " | ".join(h for _, h in cols) + " | Expectation |")
    lines.append("|---" * (len(cols) + 2) + "|")
    for name, r in results.items():
        r = dict(r)
        r["supply_delta"] = f"{r['genesis_supply']}→{r['final_supply']}"
        cells = " | ".join(str(r[k]) for k, _ in cols)
        lines.append(f"| {name} | {cells} | {EXPECT.get(name, '')} |")
    return "\n".join(lines)


def main() -> None:
    results = run_all()
    table = to_markdown(results)
    print("\nZhixingGraph economic simulation — scenario results\n")
    print(table)
    print("\nMetrics: Supply(gen→fin)=genesis vs final $COG supply; NetEmit/ep="
          "avg net emission per epoch (mint-burn-slash); Gini=inequality of "
          "contributor earnings (0=equal); ValleyBal=cross-domain balance "
          "min/max node count (1=evenly filled); FakePass=share of fake "
          "submissions accepted; AtkROI/HonROI=attacker vs honest NET "
          "return-on-stake, (earned-slashed)/staked (<0 means net loss).")
    if "--md" in sys.argv:
        with open("sim/RESULTS.md", "w") as f:
            f.write("# Simulation results (auto-generated by sim/run.py)\n\n")
            f.write(table + "\n")
        print("\nWrote sim/RESULTS.md")


if __name__ == "__main__":
    main()
